services:
  web:
    volumes:
      - ./web:/app/web
      - ./stdlib:/app/stdlib
    command:
      - uv
      - run
      - uvicorn
      - web.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /app/web
      - --reload-dir
      - /app/stdlib
      - --reload-include
      - "*.html"

  bot:
    volumes:
      - data:/app/data
      - ./bot:/app/bot
      - ./stdlib:/app/stdlib
